apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-year2023-deployment
  namespace: dev
  labels:
    app: year2023
    env: dev
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 100%
    type: RollingUpdate
  selector:
    matchLabels:
      app: year2023
      env: dev
  template:
    metadata:
      labels:
        app: year2023
        env: dev
    spec:
      containers:
        - name: year2023-ms
          image: 559220132560.dkr.ecr.ap-south-1.amazonaws.com/year2023:latest
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
          ports:
            - containerPort: 8080
              name: api
          volumeMounts:
            - mountPath: /app/config
              name: application-config
      volumes:
        - name: application-config
          configMap:
            name: dev-year2023-application-config